const stripe_key = 'pk_test_T0ULtPYHaPA4ipD3CBCng3MA00AImGD2g4'

export const CREATE_STRIPE_CUSTOMER = 'CREATE_STRIPE_CUSTOMER'
export const CHARGE_STRIPE_CUSTOMER = 'CHARGE_STRIPE_CUSTOMER'
export const STORE_PAYMENT_INTENT = 'STORE_PAYMENT_INTENT'

export default stripe_key
